server:
  port: 8080
  servlet:
    context-path: /petra

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/springdata
    username : dev
    password : dev

#JPA
# JPA ??? ?? ??(generate-ddl)
#   none: ?? ???? ??
#   create: ?? ?? ??
#   create-drop: ?? ? ?? ? ?? ? ??
#   update: ?? ? Entity ???? DB ??? ??? ???? DB?? ???? ?? ???, ?? ?? (??? ?? ??)
#   validate: ?? ? Entity ???? DB ??? ??? ???? ???? ?? (??? ?? ??)
# JPA SQL ?? ??(show-sql)
#   true or false
# JPA SQL ?? ??(show-sql)
#   true or false

jpa:
  properties:
    dialect : org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      format_sql: false     # ?? ?? ??
  show-sql: true            # ?? ?? ??
  generate-ddl: update    # ????? @Entity ?? ??? DDL? ???? DB ??

logging:
  config: classpath:log4j2.xml